function User(options) {
    let obj = {
        'odata.type': null,
        objectType: null,
        objectId: null,
        deletionTimestamp: null,
        accountEnabled: null,
        ageGroup: null,
        assignedLicenses: null,
        assignedPlans: null,
        city: null,
        companyName: null,
        consentProvidedForMinor: null,
        country: null,
        createdDateTime: null,
        creationType: null,
        department: null,
        dirSyncEnabled: null,
        displayName: null,
        employeeId: null,
        facsimileTelephoneNumber: null,
        givenName: null,
        immutableId: null,
        isCompromised: null,
        jobTitle: null,
        lastDirSyncTime: null,
        legalAgeGroupClassification: null,
        mail: null,
        mailNickname: null,
        mobile: null,
        onPremisesDistinguishedName: null,
        onPremisesSecurityIdentifier: null,
        otherMails: null,
        passwordPolicies: null,
        passwordProfile: null,
        physicalDeliveryOfficeName: null,
        postalCode: null,
        preferredLanguage: null,
        provisionedPlans: null,
        provisioningErrors: null,
        proxyAddresses: null,
        refreshTokensValidFromDateTime: null,
        showInAddressList: null,
        signInNames: null,
        sipProxyAddress: null,
        state: null,
        streetAddress: null,
        surname: null,
        telephoneNumber: null,
        usageLocation: null,
        userIdentities: null,
        userPrincipalName: null,
        userState: null,
        userStateChangedOn: null,
        userType: null,
        issqluser: null,   
    }
    Object.assign(obj, options)
    return obj
}

module.exports = User